apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag", 
            "name": "cicd-demo:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: cicd
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 300m
        image: image-registry.openshift-image-registry.svc:5000/cicd-demo/cicd-demo
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config