FROM maven:3-openjdk-11 as builder
WORKDIR /tmp
COPY pom.xml ./
COPY src ./src
RUN mvn package -DskipTests

FROM openjdk:11
COPY --from=builder /tmp/target/*.jar ./app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
